[package]
name = "psb-gpu-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
cudarc = { version = "0.12", features = ["cuda-12020", "nccl"] }
rand = "0.8"
divan = "0.1.21"

[[bench]]
name = "masked_xor_bench"
harness = false

[[bench]]
name = "chacha_bench"
harness = false